class flow{
    selector = {
        btn_addNew : "div[class='right-field-area'] > :nth-child(2) > :nth-child(1)",
        btn_thactac : ".vue3-easy-data-table__body > tr:eq(0) > :nth-child(7) > :nth-child(1) > :nth-child(1)",
        btn_edit : ".vue3-easy-data-table__body > tr:eq(0) > :nth-child(7) > :nth-child(1) > :nth-child(2)",
        btn_info : ".v-list-item__content > :nth-child(1)",
        btn_copy : ".v-list-item__content > :nth-child(2)",
        btn_delete : ".v-list-item__content > :nth-child(3)",
        btn_flowSetting_step : ".step-by-step-footer > .add-new-step > span",
        btn_flowSetting_delete : "a[class='trash-card flex-center']",
        btn_flowSetting_confirm_YES : "button[class='v-btn v-btn--elevated v-theme--light bg-success v-btn--density-default v-btn--size-default v-btn--variant-elevated btn-success btn-success']",
        btn_flowSetting_confirm_YES_2 : "button[class='v-btn v-btn--elevated v-theme--light v-btn--density-default v-btn--size-default v-btn--variant-elevated btn-yes mr-5']",
        btn_flowSetting_refreshStep : "a[class='refesh-card flex-center']",
        btn_flowSetting_submit : "button[class='save-btn d-flex flex-row align-center justify-center']",
        btn_flowSetting_cancel : "button[class='cancel-btn d-flex flex-row align-center justify-center']",
        btn_rowPerPage : ".rows-input__wrapper > .rows-input",
        btn_rowPerPage_listName : "ul[class='select-items show'] li",
        flow_name: "div[class='v-col-sm-6 v-col-12'] > .d-flex > .v-input > .v-input__control > .v-field > .v-field__field > input",
        department: "#department-flow > #multi-select > :nth-child(1)",
        department_listName: "#department-flow > #multi-select > :nth-child(2) > .list-items > .list-items-content > li",
        group: "#group-flow > #multi-select > :nth-child(1) > #select-row",
        group_listName: "#group-flow > #multi-select > :nth-child(2) > .list-items > .list-items-content > li",
        position: "#position-flow > #multi-select > .label-select > #select-row",
        position_listName: "#position-flow > #multi-select > .multi-select-dropdown > .list-items > .list-items-content > li",
        detail_step_1: "#step-0 > .step-info-area > [style='padding: 0px 15px 15px;']",
        detail_Name_VN: ".step-info-area > [style='padding: 0px 15px 15px;'] > .py-0 > .v-col-11 > .v-row > :nth-child(1) > .flex-column > :nth-child(3) > .v-input__control > .v-field > .v-field__field > input",
        detail_Name_EN: ".step-info-area > [style='padding: 0px 15px 15px;'] > .py-0 > .v-col-11 > .v-row > :nth-child(1) > .flex-column > :nth-child(5) > .v-input__control > .v-field > .v-field__field > input",
        detail_Name_JP: ".step-info-area > [style='padding: 0px 15px 15px;'] > .py-0 > .v-col-11 > .v-row > :nth-child(1) > .flex-column > :nth-child(8) > .v-input__control > .v-field > .v-field__field > input",
        detail_checkbox_userSubmit: ".step-info-area > [style='padding: 0px 15px 15px;'] > .py-0 > .v-col-11 > .v-row > :nth-child(2) > .flex-column > :nth-child(2) > input",
        detail_position: ".step-info-area > [style='padding: 0px 15px 15px;'] > .py-0 > .v-col-11 > .v-row > :nth-child(2) > .flex-column > :nth-child(4)",
        detail_position_listName: ".step-info-area > [style='padding: 0px 15px 15px;'] > .py-0 > .v-col-11 > .v-row > :nth-child(2) > .flex-column > :nth-child(4) > .d-flex > .multi-select-dropdown > .list-items > .list-items-content > li",
        detail_employee: ".step-info-area > [style='padding: 0px 15px 15px;'] > .py-0 > .v-col-11 > .v-row > :nth-child(2) > .flex-column > :nth-child(7)",
        detail_employee_listName: ".step-info-area > [style='padding: 0px 15px 15px;'] > .py-0 > .v-col-11 > .v-row > :nth-child(2) > .flex-column > :nth-child(7) > #multi-select > .multi-select-dropdown > .list-items > .list-items-content > li",
        detail_type: "div[class='list-group-item'] div[class='w-100 position-relative step-by-step-area'] div[class='step-info-area'] div[style='padding: 0px 15px 15px;'] div[class='v-row p-0 m-0'] div[class='v-col-sm-12 v-col-md-12 v-col-lg-2 v-col-12'] div[class='d-flex flex-column w-100 card-step'] div[class='w-100 position-relative select-drop-down']",
        detail_type_listName: "div[class='list-group-item'] div[class='w-100 position-relative step-by-step-area'] div[class='step-info-area'] div[style='padding: 0px 15px 15px;'] div[class='v-row p-0 m-0'] div[class='v-col-sm-12 v-col-md-12 v-col-lg-2 v-col-12'] div[class='d-flex flex-column w-100 card-step'] div[class='w-100 position-relative select-drop-down'] > div[class='d-flex align-center flex-row'] > .multi-select-dropdown > .list-items > .list-items-content > li",
        detail_Approve_nameVN: ".w-100 > .v-row > :nth-child(1) > :nth-child(2)",
        detail_Approve_nameEN: ".w-100 > .v-row > :nth-child(1) > :nth-child(4)",
        detail_Approve_nameJP: ".w-100 > .v-row > :nth-child(1) > :nth-child(6)",
        detail_Deny_nameVN: ".w-100 > .v-row > :nth-child(2) > :nth-child(2)",
        detail_Deny_nameEN: ".w-100 > .v-row > :nth-child(2) > :nth-child(4)",
        detail_Deny_nameJP: ".w-100 > .v-row > :nth-child(2) > :nth-child(6)",
        notifi_box: "div[class='v-overlay__content v-snackbar__wrapper v-theme--light bg-success v-snackbar--variant-elevated scroll-x-reverse-transition-enter-active scroll-x-reverse-transition-enter-to']",
        row : "tbody[class='vue3-easy-data-table__body'] tr"
    }
}
module.exports = new flow();
