class Role{
    selector = {
        btn_addNew : "button[class='v-btn v-btn--elevated v-theme--light v-btn--density-default v-btn--size-default v-btn--variant-elevated btn-add']",
        btn_thaotac : ".vue3-easy-data-table__body > :nth-child(1) > :nth-child(8) > :nth-child(1) > :nth-child(1)",
        btn_edit : ".vue3-easy-data-table__body > :nth-child(1) > :nth-child(8) > :nth-child(1) > :nth-child(2)",
        btn_info : "div[class='v-list-item v-theme--light v-list-item--density-default v-list-item--one-line v-list-item--variant-text p-0 m-0 list-item'] > .v-list-item__content > .v-list-item-title:eq(0)",
        btn_copy : "div[class='v-list-item v-theme--light v-list-item--density-default v-list-item--one-line v-list-item--variant-text p-0 m-0 list-item'] > .v-list-item__content > .v-list-item-title:eq(1)",
        btn_delete : "div[class='v-list-item v-theme--light v-list-item--density-default v-list-item--one-line v-list-item--variant-text p-0 m-0 list-item'] > .v-list-item__content > .v-list-item-title:eq(2)",
        btn_rowPerPage : ".vue3-easy-data-table__footer > .pagination__rows-per-page > .easy-data-table__rows-selector > .rows-input__wrapper",
        btn_rowPerPage_listName : ".vue3-easy-data-table__footer > .pagination__rows-per-page > .easy-data-table__rows-selector > .select-items > li",
        btn_submit : ".btn-success",
        btn_cancel : ".btn-danger",
        btn_confirm_submit : ".button-container > button:eq(0)",
        btn_confirm_cancel : ".button-container > button:eq(2)",
        search_bar : ".search-input",
        notification : ".v-snackbar__content",
        row : ".vue3-easy-data-table__body > tr",
        board_title : ".title:eq(1)",
        authority_department : ".row:eq(0) > .col:eq(0) > #multi-select",
        authority_department_listName : ".row:eq(0) > .col:eq(0) > #multi-select > .multi-select-dropdown > .list-items > .list-items-content > li",
        authority_group : ".row:eq(0) > .col:eq(1) > #multi-select",
        authority_group_listName : ".row:eq(0) > .col:eq(1) > #multi-select > .multi-select-dropdown > .list-items > .list-items-content > li",
        authority_position : ".row:eq(1) > .col:eq(0) > #multi-select",
        authority_position_listName : ".row:eq(1) > .col:eq(0) > #multi-select > .multi-select-dropdown > .list-items > .list-items-content > li",
        authority_employee : ".row:eq(1) > .col:eq(1) > #multi-select",
        authority_employee_listName : ".row:eq(1) > .col:eq(1) > #multi-select > .multi-select-dropdown > .list-items > .list-items-content > li",
        Role : ".row:eq(2) > .col:eq(0) > #multi-select",
        Role_listName : ".row:eq(2) > .col:eq(0) > #multi-select > .multi-select-dropdown > .list-items > .list-items-content > li",
        Time_From : ".row:eq(3) > .col:eq(0) > #form-calendar",
        Time_To : ".row:eq(3) > .col:eq(1) > #form-calendar",
        goal_department : ".row:eq(4) > .col:eq(0) > #multi-select",
        goal_department_listName : ".row:eq(4) > .col:eq(0) > #multi-select > .multi-select-dropdown > .list-items > .list-items-content > li",
        goal_group : ".row:eq(4) > .col:eq(1) > #multi-select",
        goal_group_listName : ".row:eq(4) > .col:eq(1) > #multi-select > .multi-select-dropdown > .list-items > .list-items-content > li",
        goal_position : ".row:eq(5) > .col:eq(0) > #multi-select",
        goal_position_listName : ".row:eq(5) > .col:eq(0) > #multi-select > .multi-select-dropdown > .list-items > .list-items-content > li",
        goal_employee : ".row:eq(5) > .col:eq(1) > #multi-select",
        goal_employee_listName : ".row:eq(5) > .col:eq(1) > #multi-select > .multi-select-dropdown > .list-items > .list-items-content > li",
        total_count : ".pagination__items-index",
        page_count : ".buttons-pagination > .item",

    }
}
module.exports = new Role();
